import type { PermissionArea, PermissionRiskLevel, SecurityPermissionRight, SecurityRoleKey } from './permissionMatrixTypes';

const owner: SecurityRoleKey[] = ['Owner', 'SysAdmin'];
const manager: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager'];
const supervisor: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'Supervisor'];
const cashier: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Cashier'];
const stock: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'StockController'];
const delivery: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'DeliveryStaff'];
const accountant: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'Accountant'];
const viewer: SecurityRoleKey[] = ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff', 'Viewer'];

const highRisk = new Set([
  'sales.void',
  'sales.return',
  'sales.cashDrawer.open',
  'sales.endOfDay.run',
  'shift.close',
  'shift.override',
  'cashDrawer.release',
  'terminal.readinessCheck',
  'stockAdjustment.post',
  'stocktake.post',
  'openingBalance.post',
  'goodsReceiving.post',
  'delivery.cashReview',
  'delivery.cashHandover',
  'accounting.approve',
  'ownerDesk.accountingDesk.paymentPosting.markSettled',
  'ownerDesk.accountingDesk.paymentPosting.flagVariance',
  'ownerDesk.accountingDesk.paymentPosting.createBIWarning',
  'financialControl.accounts.manage',
  'financialControl.cashPlan.manage',
  'financialControl.ownerDecisions.manage',
  'bi.advice.escalate',
  'bi.reorderBlock.override',
  'sync.conflict.resolve'
]);

const criticalRisk = new Set(['settings.permissions.edit', 'staff.permissions.assign', 'sync.clearSynced', 'audit.lockedDayReview']);

const labels: Record<string, string> = {
  view: 'View',
  open: 'Open',
  complete: 'Complete',
  hold: 'Hold',
  discount: 'Discount',
  priceChange: 'Price Change',
  void: 'Void',
  return: 'Return',
  reprintReceipt: 'Reprint Receipt',
  createRequest: 'Create Request',
  createDirect: 'Create Direct',
  edit: 'Edit',
  creditView: 'Credit View',
  purchaseHistoryView: 'Purchase History',
  create: 'Create',
  activate: 'Activate',
  block: 'Block',
  map: 'Map',
  validate: 'Validate',
  approve: 'Approve',
  import: 'Import',
  send: 'Send',
  post: 'Post',
  assign: 'Assign',
  broadcast: 'Broadcast',
  track: 'Track',
  dispatch: 'Dispatch',
  verifyCode: 'Verify Code',
  collectCash: 'Collect Cash',
  cashHandover: 'Cash Handover',
  cancel: 'Cancel',
  performance: 'Performance',
  export: 'Export',
  override: 'Override',
  reject: 'Reject',
  retry: 'Retry',
  run: 'Run',
  disable: 'Disable',
  resetPin: 'Reset PIN',
  unlock: 'Unlock',
  configure: 'Configure'
};

const titleCase = (value: string) => value.split('.').map((part) => labels[part] || part.replace(/([A-Z])/g, ' $1').replace(/\b\w/g, (letter) => letter.toUpperCase()).trim()).join(' ');

const riskFor = (permissionKey: string): PermissionRiskLevel => {
  if (criticalRisk.has(permissionKey)) return 'Critical';
  if (highRisk.has(permissionKey)) return 'High';
  if (permissionKey.includes('approve') || permissionKey.includes('edit') || permissionKey.includes('create') || permissionKey.includes('export')) return 'Medium';
  return 'Low';
};

let sortCounter = 0;
const right = (area: PermissionArea, permissionKey: string, defaultRoles: SecurityRoleKey[], description: string, systemLocked = false): SecurityPermissionRight => {
  const riskLevel = riskFor(permissionKey);
  return {
    permissionKey,
    label: titleCase(permissionKey),
    area,
    description,
    riskLevel,
    requiresApproval: riskLevel === 'High' || riskLevel === 'Critical',
    systemLocked,
    defaultRoles,
    warningNote: riskLevel === 'High' || riskLevel === 'Critical' ? 'Changing this right affects high-risk operational controls.' : undefined,
    sortOrder: sortCounter += 10
  };
};

export const securityRightsCatalog: SecurityPermissionRight[] = [
  right('Dashboard', 'dashboard.view', viewer, 'Open the main dashboard overview.', true),
  right('Dashboard', 'ownerDesk.view', owner, 'Open the owner review desk.'),
  right('Dashboard', 'bi.summary.view', manager, 'View summarized BI cards and risk indicators.'),

  right('Sales', 'sales.open', cashier, 'Open and use the sales terminal.'),
  right('Sales', 'sales.complete', cashier, 'Complete a sale and issue the receipt.'),
  right('Sales', 'sales.hold', cashier, 'Place a sale on hold.'),
  right('Sales', 'sales.heldSale.delete', supervisor, 'Delete held or draft sales.'),
  right('Sales', 'sales.heldSale.reopenExpired', manager, 'Reopen expired held sales.'),
  right('Sales', 'sales.discount', supervisor, 'Apply a discount to a sale.'),
  right('Sales', 'sales.priceChange', supervisor, 'Change a selling price at the terminal.'),
  right('Sales', 'sales.void', supervisor, 'Void a sale or sale line.'),
  right('Sales', 'sales.return', supervisor, 'Process a return or refund request.'),
  right('Sales', 'sales.reprintReceipt', cashier, 'Reprint a receipt.'),
  right('Sales', 'sales.creditRedeem', accountant, 'Redeem local customer credit during a sale.'),
  right('Sales', 'sales.loyalty', supervisor, 'Redeem local loyalty rewards during a sale.'),
  right('Sales', 'sales.accountSale', accountant, 'Apply customer account sale payment mode.'),
  right('Sales', 'payment.capture', cashier, 'Capture local payment lines during checkout.'),
  right('Sales', 'sales.viewHistory', viewer, 'View sales history records.'),
  right('Sales', 'sales.profitSnapshot.view', accountant, 'View local Sales Profit Snapshot estimates.'),
  right('Sales', 'sales.profitSnapshot.generate', accountant, 'Generate local Sales Profit Snapshot estimates.'),
  right('Sales', 'sales.profitSnapshot.export', accountant, 'Prepare Sales Profit Snapshot export placeholders.'),
  right('Sales', 'sales.profitSnapshot.print', accountant, 'Prepare Sales Profit Snapshot print placeholders.'),
  right('Sales', 'sales.miscellaneous.create', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Cashier'], 'Create BI-flagged miscellaneous non-inventory sale lines.'),
  right('Sales', 'sales.miscellaneous.review', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant'], 'Review miscellaneous non-inventory sale lines.'),
  right('Sales', 'sales.miscellaneous.approve', ['Owner', 'SysAdmin', 'Manager'], 'Approve miscellaneous non-inventory sale lines.'),
  right('Sales', 'sales.cashDrawer.open', supervisor, 'Open the cash drawer outside the normal sale flow.'),
  right('Sales', 'sales.endOfDay.run', manager, 'Run end-of-day sales close routines.'),
  right('Sales', 'shift.view', cashier, 'View Shift Control and current terminal readiness.'),
  right('Sales', 'shift.open', cashier, 'Open a local terminal shift.'),
  right('Sales', 'shift.close', cashier, 'Close an assigned local terminal shift.'),
  right('Sales', 'shift.eodReport.view', accountant, 'View shift EOD reports and local summaries.'),
  right('Sales', 'shift.eodReport.print', accountant, 'Print shift EOD reports or use device Save as PDF.'),
  right('Sales', 'cashDrawer.assign', supervisor, 'Assign a local cash drawer to a terminal shift.'),
  right('Sales', 'cashDrawer.release', manager, 'Release an assigned local cash drawer.'),
  right('Sales', 'terminal.activate', manager, 'Activate local POS terminals after readiness review.'),
  right('Sales', 'terminal.deactivate', manager, 'Deactivate local POS terminals during control review.'),
  right('Sales', 'terminal.history.view', supervisor, 'View detailed closed terminal period history.'),
  right('Sales', 'terminal.readinessCheck', supervisor, 'Run local terminal readiness checks before activation or shift open.'),
  right('Sales', 'shift.recovery.restore', cashier, 'Restore recoverable local shift state on this device.'),
  right('Sales', 'shift.override', manager, 'Override selected shift close checks during local review.'),

  right('Customers', 'customers.view', viewer, 'View customer records and lookup results.'),
  right('Customers', 'customers.createRequest', cashier, 'Request creation of a customer record.'),
  right('Customers', 'customers.createDirect', supervisor, 'Create a customer record directly.'),
  right('Customers', 'customers.edit', supervisor, 'Edit approved customer records.'),
  right('Customers', 'customers.creditView', accountant, 'View customer credit status and exposure.'),
  right('Customers', 'customers.purchaseHistoryView', viewer, 'View customer purchase history.'),

  right('Inventory', 'inventory.view', stock, 'View inventory and stock balances.'),
  right('Inventory', 'productMaster.view', stock, 'View product master records.'),
  right('Inventory', 'productMaster.create', stock, 'Create product master records.'),
  right('Inventory', 'productMaster.edit', stock, 'Edit product master records.'),
  right('Inventory', 'inventory.product.create', stock, 'Create product records from inventory workflows.'),
  right('Inventory', 'inventory.product.createDraft', stock, 'Create draft product records.'),
  right('Inventory', 'inventory.product.reviewNewFromPO', stock, 'Review products created from Purchase Orders.'),
  right('Inventory', 'productMaster.activate', manager, 'Activate product master records.'),
  right('Inventory', 'productMaster.block', manager, 'Block product master records.'),
  right('Inventory', 'purchaseOrder.productSearch', stock, 'Search Product Master from Purchase Orders.'),
  right('Inventory', 'purchaseOrder.productCreateFromPO', stock, 'Create draft products from Purchase Orders.'),
  right('Inventory', 'productImport.view', stock, 'View product import batches.'),
  right('Inventory', 'inventory.import.view', stock, 'View Inventory Import Mapping Wizard.'),
  right('Inventory', 'inventory.import.create', stock, 'Create local inventory import batches.'),
  right('Inventory', 'inventory.import.map', stock, 'Map inventory import columns.'),
  right('Inventory', 'inventory.import.template.view', stock, 'View inventory import mapping templates.'),
  right('Inventory', 'inventory.import.template.manage', manager, 'Manage inventory import mapping templates.'),
  right('Inventory', 'inventory.import.validate', stock, 'Validate inventory import mappings and rows.'),
  right('Inventory', 'inventory.import.submitApproval', stock, 'Submit inventory import batches for approval.'),
  right('Inventory', 'inventory.import.approve', manager, 'Approve inventory import batches.'),
  right('Inventory', 'inventory.import.post', manager, 'Post approved inventory import locally.'),
  right('Inventory', 'inventory.import.reject', manager, 'Reject inventory import batches.'),
  right('Inventory', 'inventory.import.cancel', stock, 'Cancel draft inventory import batches.'),
  right('Inventory', 'inventory.import.export', stock, 'Export inventory import previews and issues.'),
  right('Inventory', 'inventory.import.print', stock, 'Print inventory import summaries and issue reports.'),
  right('Inventory', 'inventory.import.createTask', stock, 'Create local tasks from import issues.'),
  right('Inventory', 'inventory.import.createBIWarning', stock, 'Create local BI warnings from import issues.'),
  right('Inventory', 'productImport.create', stock, 'Create product import batches.'),
  right('Inventory', 'productImport.map', stock, 'Map product import columns.'),
  right('Inventory', 'productImport.validate', stock, 'Validate product import rows.'),
  right('Inventory', 'productImport.approve', manager, 'Approve product import batches.'),
  right('Inventory', 'productImport.import', manager, 'Post approved product import batches.'),

  right('Procurement', 'purchaseOrder.view', stock, 'View purchase orders.'),
  right('Procurement', 'purchaseOrder.create', stock, 'Create purchase orders.'),
  right('Procurement', 'purchaseOrder.approve', manager, 'Approve purchase orders.'),
  right('Procurement', 'purchaseOrder.send', manager, 'Send purchase orders to suppliers.'),
  right('Procurement', 'goodsReceiving.view', stock, 'View goods receiving notes.'),
  right('Procurement', 'goodsReceiving.create', stock, 'Create goods receiving notes.'),
  right('Procurement', 'goodsReceiving.post', manager, 'Post goods receiving into stock.'),
  right('Procurement', 'supplierReturn.view', stock, 'View supplier returns.'),
  right('Procurement', 'supplierReturn.create', stock, 'Create supplier returns.'),
  right('Procurement', 'supplierReturn.post', manager, 'Post supplier returns.'),

  right('Stock Control', 'stockAdjustment.view', stock, 'View stock adjustments.'),
  right('Stock Control', 'stockAdjustment.create', stock, 'Create stock adjustments.'),
  right('Stock Control', 'stockAdjustment.approve', manager, 'Approve stock adjustments.'),
  right('Stock Control', 'stockAdjustment.post', manager, 'Post stock adjustments.'),
  right('Stock Control', 'stocktake.view', stock, 'View stocktakes.'),
  right('Stock Control', 'stocktake.create', stock, 'Create stocktakes.'),
  right('Stock Control', 'stocktake.approve', manager, 'Approve stocktakes.'),
  right('Stock Control', 'stocktake.post', manager, 'Post stocktakes.'),
  right('Stock Control', 'stockTransfer.view', stock, 'View stock transfers.'),
  right('Stock Control', 'stockTransfer.create', stock, 'Create stock transfers.'),
  right('Stock Control', 'stockTransfer.dispatch', stock, 'Dispatch stock transfers.'),
  right('Stock Control', 'stockTransfer.receive', stock, 'Receive stock transfers.'),
  right('Stock Control', 'openingBalance.view', stock, 'View opening balances.'),
  right('Stock Control', 'openingBalance.create', stock, 'Create opening balances.'),
  right('Stock Control', 'openingBalance.approve', manager, 'Approve opening balances.'),
  right('Stock Control', 'openingBalance.post', manager, 'Post opening balances.'),

  right('Delivery', 'delivery.view', delivery, 'View delivery requests.'),
  right('Delivery', 'delivery.create', cashier, 'Create delivery requests from sales.'),
  right('Delivery', 'delivery.assign', supervisor, 'Assign deliveries.'),
  right('Delivery', 'delivery.dispatch', supervisor, 'Dispatch assigned deliveries after address, item, team, and cash checks.'),
  right('Delivery', 'delivery.broadcast', manager, 'Broadcast delivery requests.'),
  right('Delivery', 'delivery.track', delivery, 'Track assigned deliveries.'),
  right('Delivery', 'delivery.verifyCode', delivery, 'Verify customer delivery code.'),
  right('Delivery', 'delivery.complete', delivery, 'Complete assigned deliveries.'),
  right('Delivery', 'delivery.cancel', supervisor, 'Cancel delivery requests.'),
  right('Delivery', 'delivery.collectCash', delivery, 'Declare cash collected during delivery.'),
  right('Delivery', 'delivery.cashHandover', accountant, 'Accept and reconcile delivery cash handovers.'),
  right('Delivery', 'delivery.cashReview', accountant, 'Review cash collected by delivery staff.'),
  right('Delivery', 'delivery.providerManage', manager, 'Manage delivery providers.'),
  right('Delivery', 'delivery.performance', manager, 'View delivery performance and warning summaries.'),

  right('Accounting', 'accounting.view', accountant, 'View accounting readiness data.'),
  right('Accounting', 'accounting.readinessReview', accountant, 'Review accounting readiness records.'),
  right('Accounting', 'accounting.approve', manager, 'Approve accounting readiness records.'),
  right('Accounting', 'accounting.export', accountant, 'Export accounting readiness records.'),
  right('Accounting', 'chartOfAccounts.view', accountant, 'View chart of accounts.'),
  right('Accounting', 'chartOfAccounts.edit', owner, 'Edit chart of accounts placeholders.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.view', accountant, 'View Owner Desk payment posting readiness.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.markSettled', accountant, 'Mark payment mode settlement readiness locally.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.viewReceipts', accountant, 'View local receipt detail for a payment mode.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.flagVariance', accountant, 'Flag payment settlement variance for review.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.addNote', accountant, 'Add owner/accounting notes to payment posting readiness.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.createTask', accountant, 'Create local accounting task from payment posting readiness.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.createBIWarning', manager, 'Create local BI warning from payment posting readiness.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.print', accountant, 'Print payment posting readiness summary.'),
  right('Accounting', 'ownerDesk.accountingDesk.paymentPosting.export', accountant, 'Export payment posting readiness row.'),
  right('Accounting', 'financialControl.view', accountant, 'Open Financial Control management preview.'),
  right('Accounting', 'financialControl.accounts.view', accountant, 'View COA-driven cash and bank control accounts.'),
  right('Accounting', 'financialControl.accounts.manage', owner, 'Manage local financial control account mappings and active state.'),
  right('Accounting', 'financialControl.moneyIn.view', accountant, 'View money-in activity preview.'),
  right('Accounting', 'financialControl.moneyOut.view', accountant, 'View money-out activity preview.'),
  right('Accounting', 'financialControl.cashPlan.view', accountant, 'View CashPlan forecast preview.'),
  right('Accounting', 'financialControl.cashPlan.manage', manager, 'Manage CashPlan placeholder lines.'),
  right('Accounting', 'financialControl.profitability.view', accountant, 'View profitability preview.'),
  right('Accounting', 'financialControl.reserveProtection.view', accountant, 'View protected funds and reserve rules.'),
  right('Accounting', 'financialControl.ownerDecisions.view', accountant, 'View owner financial decisions.'),
  right('Accounting', 'financialControl.ownerDecisions.manage', owner, 'Approve or reject owner financial decisions.'),
  right('Accounting', 'financialControl.bi.view', manager, 'View Financial Control BI warnings.'),
  right('Accounting', 'financialControl.print', accountant, 'Print Financial Control previews.'),
  right('Accounting', 'financialControl.export', accountant, 'Export Financial Control preview rows.'),
  right('Accounting', 'financialControl.checkWriter.view', accountant, 'View the local A5 Check Writer.'),
  right('Accounting', 'financialControl.checkWriter.create', accountant, 'Create local check writer drafts.'),
  right('Accounting', 'financialControl.checkWriter.prepare', accountant, 'Prepare local checks.'),
  right('Accounting', 'financialControl.checkWriter.approve', manager, 'Approve local check previews.'),
  right('Accounting', 'financialControl.checkWriter.print', accountant, 'Print check preview documents.'),
  right('Accounting', 'financialControl.checkWriter.issueLocal', accountant, 'Mark checks issued locally without banking integration.'),
  right('Accounting', 'financialControl.checkWriter.void', manager, 'Void local check writer records.'),
  right('Accounting', 'financialControl.payee.view', accountant, 'View the local Payee Register.'),
  right('Accounting', 'financialControl.payee.manage', accountant, 'Manage local payee records.'),
  right('Accounting', 'financialControl.checkSettings.manage', owner, 'Manage check writer numbering settings.'),
  right('Accounting', 'financialControl.journal.view', accountant, 'View local journal entry previews.'),
  right('Accounting', 'financialControl.journal.create', accountant, 'Create journal entry drafts.'),
  right('Accounting', 'financialControl.journal.editDraft', accountant, 'Edit draft journal entries.'),
  right('Accounting', 'financialControl.journal.submitReview', accountant, 'Submit balanced journals for review.'),
  right('Accounting', 'financialControl.journal.markPostedPreview', accountant, 'Mark balanced journals as Posted Preview.'),
  right('Accounting', 'financialControl.journal.void', manager, 'Void local journal entries.'),
  right('Accounting', 'financialControl.journal.print', accountant, 'Print journal entry previews.'),

  right('Reports', 'reports.view', viewer, 'View reports.'),
  right('Reports', 'reports.sales', supervisor, 'View sales reports.'),
  right('Reports', 'reports.inventory', stock, 'View inventory reports.'),
  right('Reports', 'reports.delivery', delivery, 'View delivery reports.'),
  right('Reports', 'reports.accounting', accountant, 'View accounting reports.'),
  right('Reports', 'reports.export', accountant, 'Export reports.'),

  right('Approvals', 'approvals.view', supervisor, 'View approval requests.'),
  right('Approvals', 'approvals.viewDetail', supervisor, 'View approval request details.'),
  right('Approvals', 'approvals.startReview', supervisor, 'Start local approval review.'),
  right('Approvals', 'approvals.approve', supervisor, 'Approve approval requests.'),
  right('Approvals', 'approvals.requestInfo', supervisor, 'Request more information for approvals.'),
  right('Approvals', 'approvals.escalate', manager, 'Escalate approvals locally.'),
  right('Approvals', 'approvals.assignReviewer', manager, 'Assign approval reviewers.'),
  right('Approvals', 'approvals.sendNotification', supervisor, 'Prepare and mark approval notifications locally.'),
  right('Approvals', 'approvals.liveChat.view', supervisor, 'View approval live chat.'),
  right('Approvals', 'approvals.liveChat.send', supervisor, 'Send local approval chat messages.'),
  right('Approvals', 'approvals.createTask', manager, 'Create task records from approvals.'),
  right('Approvals', 'approvals.createBIWarning', manager, 'Create BI warning records from approvals.'),
  right('Approvals', 'approvals.openRelatedRecord', supervisor, 'Open related approval source records locally.'),
  right('Approvals', 'approvals.print', supervisor, 'Print approval records.'),
  right('Approvals', 'approvals.export', supervisor, 'Export approval records.'),
  right('Approvals', 'approvals.notificationOutbox.view', supervisor, 'View approval notification outbox.'),
  right('Approvals', 'approvals.audit.view', supervisor, 'View approval audit trail.'),
  right('Approvals', 'taskDesk.view', supervisor, 'View Task Desk workflow queue.'),
  right('Approvals', 'taskDesk.create', manager, 'Create local workflow tasks.'),
  right('Approvals', 'taskDesk.viewDetail', supervisor, 'View task details and timelines.'),
  right('Approvals', 'taskDesk.startReview', supervisor, 'Start task review locally.'),
  right('Approvals', 'taskDesk.addNote', supervisor, 'Add local task notes.'),
  right('Approvals', 'taskDesk.reassign', manager, 'Reassign local workflow tasks.'),
  right('Approvals', 'taskDesk.pendingInfo', supervisor, 'Mark task pending information.'),
  right('Approvals', 'taskDesk.escalate', manager, 'Escalate task locally.'),
  right('Approvals', 'taskDesk.complete', supervisor, 'Complete local tasks.'),
  right('Approvals', 'taskDesk.close', manager, 'Close local tasks.'),
  right('Approvals', 'taskDesk.createApproval', manager, 'Create local approval from a task.'),
  right('Approvals', 'taskDesk.createBIWarning', manager, 'Create local BI warning from a task.'),
  right('Approvals', 'taskDesk.openRelatedRecord', supervisor, 'Open related task source record locally.'),
  right('Approvals', 'workflow.openRelatedRecord', supervisor, 'Open related records through the shared workflow router.'),
  right('Approvals', 'notifications.view', supervisor, 'View shared workflow notification inbox rows.'),
  right('Approvals', 'notifications.markRead', supervisor, 'Mark shared workflow notifications as read.'),
  right('Approvals', 'notifications.createTask', manager, 'Create follow-up tasks from shared workflow notifications.'),
  right('Approvals', 'notifications.dismiss', supervisor, 'Dismiss shared workflow notifications.'),
  right('Approvals', 'taskDesk.print', supervisor, 'Print task detail.'),
  right('Approvals', 'taskDesk.export', supervisor, 'Export task row.'),
  right('Approvals', 'approvals.approveLowRisk', supervisor, 'Approve low-risk requests.'),
  right('Approvals', 'approvals.approveHighRisk', manager, 'Approve high-risk requests.'),
  right('Approvals', 'approvals.override', manager, 'Override approval rules.'),
  right('Approvals', 'approvals.reject', supervisor, 'Reject approval requests.'),

  right('Sync', 'sync.view', viewer, 'View sync desk status.'),
  right('Sync', 'sync.retry', stock, 'Retry failed sync records.'),
  right('Sync', 'sync.batch.create', stock, 'Create sync batches.'),
  right('Sync', 'sync.batch.run', manager, 'Run sync batches.'),
  right('Sync', 'sync.conflict.view', supervisor, 'View sync conflicts.'),
  right('Sync', 'sync.conflict.resolve', manager, 'Resolve sync conflicts.'),
  right('Sync', 'sync.export', accountant, 'Export sync reports.'),
  right('Sync', 'sync.clearSynced', owner, 'Clear synced local queue records.'),

  right('Help Desk', 'helpDesk.view', viewer, 'View the in-app Help Desk Book.'),
  right('Help Desk', 'helpDesk.print', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController'], 'Print local help articles.'),
  right('Help Desk', 'helpDesk.copy', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff'], 'Copy local help guidance text.'),
  right('Help Desk', 'helpDesk.reportIssue', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff'], 'Report a local/mock help content issue.'),
  right('Help Desk', 'helpDesk.openFunctionLinks', ['Owner', 'SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff'], 'Open related POS functions from help articles.'),

  right('Settings', 'settings.view', manager, 'View Settings.'),
  right('Settings', 'settings.business.edit', owner, 'Edit business settings.'),
  right('Settings', 'settings.hardware.edit', owner, 'Edit hardware settings.'),
  right('Settings', 'settings.tax.edit', owner, 'Edit tax settings.'),
  right('Settings', 'settings.staff.edit', owner, 'Edit staff settings.'),
  right('Settings', 'settings.permissions.edit', owner, 'Edit role permission matrix.', true),
  right('Settings', 'businessProfile.view', viewer, 'View basic business profile details.'),
  right('Settings', 'businessProfile.edit', manager, 'Edit business profile details.'),
  right('Settings', 'businessRegistration.view', ['Owner', 'SysAdmin', 'Manager', 'Accountant'], 'View business registration details.'),
  right('Settings', 'businessRegistration.edit', owner, 'Edit business registration details.'),
  right('Settings', 'businessRegistration.dashboardView', ['Owner', 'SysAdmin', 'Manager', 'Accountant'], 'Show registration details on the dashboard.'),
  right('Settings', 'businessTax.view', ['Owner', 'SysAdmin', 'Manager', 'Accountant'], 'View VAT and tax details.'),
  right('Settings', 'businessTax.edit', owner, 'Edit VAT and tax details.'),
  right('Settings', 'businessAdministrator.view', ['Owner', 'SysAdmin', 'Manager', 'Accountant'], 'View accountant and administrator contacts.'),
  right('Settings', 'businessAdministrator.edit', owner, 'Edit accountant and administrator contacts.'),

  right('Staff Access', 'staff.view', manager, 'View staff access records.'),
  right('Staff Access', 'staff.create', owner, 'Create staff users.'),
  right('Staff Access', 'staff.edit', owner, 'Edit staff users.'),
  right('Staff Access', 'staff.disable', owner, 'Disable staff users.'),
  right('Staff Access', 'staff.resetPin', owner, 'Reset staff PIN placeholders.'),
  right('Staff Access', 'staff.permissions.assign', owner, 'Assign security rights.', true),
  right('Staff Access', 'staff.session.unlock', owner, 'Unlock staff sessions.'),

  right('Hardware', 'hardware.view', manager, 'View hardware status.'),
  right('Hardware', 'hardware.cashDrawer.configure', owner, 'Configure cash drawer.'),
  right('Hardware', 'hardware.printer.configure', owner, 'Configure receipt printer.'),
  right('Hardware', 'hardware.scanner.configure', owner, 'Configure barcode scanner.'),
  right('Hardware', 'hardware.fiscalDevice.configure', owner, 'Configure fiscal device placeholder.'),

  right('BI', 'bi.view', manager, 'View BI desk.'),
  right('BI', 'bi.management.view', manager, 'View Management BI dashboard and domain scores.'),
  right('BI', 'bi.management.generate', manager, 'Generate deterministic Management BI outputs.'),
  right('BI', 'bi.riskReview', manager, 'Review BI risk signals.'),
  right('BI', 'bi.export', accountant, 'Export BI outputs.'),
  right('BI', 'bi.rules.manage', owner, 'Manage BI rules placeholders.'),
  right('BI', 'bi.advice.view', manager, 'View deterministic BI advice records.'),
  right('BI', 'bi.advice.generate', manager, 'Generate deterministic BI advice from local trigger logs.'),
  right('BI', 'bi.advice.assign', manager, 'Assign BI advice to staff, roles, or desks.'),
  right('BI', 'bi.advice.resolve', supervisor, 'Resolve BI advice after review.'),
  right('BI', 'bi.advice.dismiss', manager, 'Dismiss BI advice after review.'),
  right('BI', 'bi.advice.escalate', manager, 'Escalate BI advice to Owner review.'),
  right('BI', 'bi.advice.createTask', supervisor, 'Create local task placeholders from BI advice.'),
  right('BI', 'bi.actionPoints.view', supervisor, 'View BI management action points.'),
  right('BI', 'bi.actionPoints.manage', manager, 'Start, complete, reassign, and escalate BI action points.'),
  right('BI', 'bi.reorderProtection.view', stock, 'View reorder protection warnings.'),
  right('BI', 'bi.reorderProtection.override', manager, 'Override reorder protection after manager review.'),
  right('BI', 'bi.shelfStocktake.assign', stock, 'Assign shelf stocktake action points from BI advice.'),
  right('BI', 'bi.cashRisk.view', accountant, 'View cash control BI risk outputs.'),
  right('BI', 'bi.staffRisk.view', manager, 'View staff behaviour BI risk outputs.'),
  right('BI', 'bi.taxReadiness.view', accountant, 'View VAT and tax readiness BI outputs.'),
  right('BI', 'bi.profitSnapshot.view', accountant, 'View BI profit and drawer management snapshot.'),
  right('BI', 'bi.reorderBlock.review', stock, 'Review stagnant-stock reorder block warnings.'),
  right('BI', 'bi.reorderBlock.override', manager, 'Override reorder block warnings after manager review.'),

  right('BI', 'bi.sales.operational', cashier, 'Access operational BI guidance inside the Sales Terminal.'),
  right('BI', 'bi.sales.history', supervisor, 'Access branch-wide detailed Sales History BI and summaries.'),
  right('BI', 'bi.sales.cashierPerformance', supervisor, 'Access cashier sales performance indicators and comparisons.'),
  right('BI', 'bi.customer.purchaseHistory', viewer, 'Access detailed customer purchase history and patterns.'),
  right('BI', 'bi.customer.creditAgeing', accountant, 'Access customer credit ageing reports and debtor ledgers.'),
  right('BI', 'bi.customer.creditWorthiness', accountant, 'Access credit worthiness score evaluations and risk analysis.'),
  right('BI', 'bi.customer.statement', accountant, 'Access customer account statements and transaction ledgers.'),
  right('BI', 'bi.stock.risk', stock, 'Access stock risk indicators, dead stock and low stock warnings.'),
  right('BI', 'bi.finance.owner', owner, 'Access owner-level financial performance, profit margin and drawer summaries.'),
  right('BI', 'bi.audit.exceptions', manager, 'Access cashier exceptions audit log and exception flags.'),


  right('Audit', 'audit.view', owner, 'View audit events.'),
  right('Audit', 'audit.export', owner, 'Export audit events.'),
  right('Audit', 'audit.lockedDayReview', owner, 'Review locked-day audit exceptions.', true)
];

export const securityPermissionAreas: PermissionArea[] = Array.from(new Set(securityRightsCatalog.map((right) => right.area)));
