import type { SecurityRoleDefinition, SecurityRoleHierarchyRule, SecurityRoleKey } from './permissionMatrixTypes';
import { securityRightsCatalog } from './securityRightsCatalog';

export const securityRoleDefinitions: SecurityRoleDefinition[] = [
  { roleKey: 'Owner', roleLabel: 'Owner', hierarchyLevel: 1, description: 'Full vendor owner access during build-development.', inheritsFrom: ['SysAdmin', 'Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff', 'Viewer'], systemRole: true, canBeEdited: false, defaultDashboard: 'Owner Desk', notes: 'Locked full access while build-development Owner bypass is active.' },
  { roleKey: 'SysAdmin', roleLabel: 'SysAdmin', hierarchyLevel: 2, description: 'Vendor system setup role without internal console access.', inheritsFrom: ['Manager', 'Supervisor', 'Accountant', 'StockController', 'Cashier', 'DeliveryStaff', 'Viewer'], systemRole: true, canBeEdited: true, defaultDashboard: 'Settings' },
  { roleKey: 'Manager', roleLabel: 'Manager', hierarchyLevel: 3, description: 'Operational manager with sales, oversight, selected inventory, delivery, reporting, approval, and EOD rights.', inheritsFrom: ['Supervisor', 'Cashier', 'Viewer'], systemRole: true, canBeEdited: true, defaultDashboard: 'Dashboard' },
  { roleKey: 'Supervisor', roleLabel: 'Supervisor', hierarchyLevel: 4, description: 'Floor supervisor with cashier rights and limited oversight.', inheritsFrom: ['Cashier', 'Viewer'], systemRole: true, canBeEdited: true, defaultDashboard: 'Sales Terminal' },
  { roleKey: 'Accountant', roleLabel: 'Accountant', hierarchyLevel: 5, description: 'Finance and reporting role with accounting review and export rights.', inheritsFrom: [], systemRole: true, canBeEdited: true, defaultDashboard: 'Reports' },
  { roleKey: 'StockController', roleLabel: 'Stock Controller', hierarchyLevel: 6, description: 'Inventory specialist with stock, procurement, GRN, adjustment, stocktake, and transfer rights.', inheritsFrom: [], systemRole: true, canBeEdited: true, defaultDashboard: 'Inventory' },
  { roleKey: 'Cashier', roleLabel: 'Cashier', hierarchyLevel: 7, description: 'Sales terminal role with customer lookup and basic transaction rights.', inheritsFrom: [], systemRole: true, canBeEdited: true, defaultDashboard: 'Sales Terminal' },
  { roleKey: 'DeliveryStaff', roleLabel: 'Delivery Staff', hierarchyLevel: 8, description: 'Assigned delivery tracking and code confirmation rights only.', inheritsFrom: [], systemRole: true, canBeEdited: true, defaultDashboard: 'Delivery Desk' },
  { roleKey: 'Viewer', roleLabel: 'Viewer', hierarchyLevel: 9, description: 'Read-only dashboard and report visibility.', inheritsFrom: [], systemRole: true, canBeEdited: true, defaultDashboard: 'Dashboard' }
];

export const securityRoleHierarchyRules: SecurityRoleHierarchyRule[] = securityRoleDefinitions.flatMap((role) =>
  role.inheritsFrom.map((inheritedRole) => ({
    roleKey: role.roleKey,
    inheritsFrom: inheritedRole,
    inheritanceType: role.roleKey === 'StockController' || role.roleKey === 'DeliveryStaff' || role.roleKey === 'Accountant' ? 'Area Specific' : 'Full',
    notes: `${role.roleLabel} inherits appropriate ${inheritedRole} rights in the preview matrix.`
  }))
);

const managerDirectPermissions = [
  'ownerDesk.view',
  'bi.summary.view',
  'sales.discount',
  'sales.priceChange',
  'sales.void',
  'sales.return',
  'sales.creditRedeem',
  'sales.loyalty',
  'sales.accountSale',
  'payment.capture',
  'sales.profitSnapshot.view',
  'sales.profitSnapshot.generate',
  'sales.profitSnapshot.export',
  'sales.profitSnapshot.print',
  'sales.miscellaneous.create',
  'sales.miscellaneous.review',
  'sales.miscellaneous.approve',
  'sales.endOfDay.run',
  'shift.view',
  'shift.open',
  'shift.close',
  'shift.eodReport.view',
  'shift.eodReport.print',
  'shift.recovery.restore',
  'shift.override',
  'cashDrawer.assign',
  'cashDrawer.release',
  'terminal.activate',
  'terminal.deactivate',
  'terminal.readinessCheck',
  'terminal.history.view',
  'customers.createDirect',
  'customers.edit',
  'inventory.view',
  'productMaster.view',
  'productMaster.create',
  'productMaster.edit',
  'inventory.product.create',
  'inventory.product.createDraft',
  'inventory.product.reviewNewFromPO',
  'productMaster.activate',
  'purchaseOrder.productSearch',
  'purchaseOrder.productCreateFromPO',
  'productImport.view',
  'inventory.import.view',
  'inventory.import.create',
  'inventory.import.map',
  'inventory.import.template.view',
  'inventory.import.template.manage',
  'inventory.import.validate',
  'inventory.import.submitApproval',
  'inventory.import.approve',
  'inventory.import.post',
  'inventory.import.reject',
  'inventory.import.cancel',
  'inventory.import.export',
  'inventory.import.print',
  'inventory.import.createTask',
  'inventory.import.createBIWarning',
  'productImport.create',
  'productImport.map',
  'productImport.validate',
  'productImport.approve',
  'productImport.import',
  'purchaseOrder.view',
  'purchaseOrder.create',
  'purchaseOrder.approve',
  'goodsReceiving.view',
  'goodsReceiving.create',
  'goodsReceiving.post',
  'stockAdjustment.view',
  'stockAdjustment.create',
  'stockAdjustment.approve',
  'stocktake.view',
  'stocktake.create',
  'stocktake.approve',
  'delivery.assign',
  'delivery.cashReview',
  'approvals.view',
  'approvals.viewDetail',
  'approvals.startReview',
  'approvals.approve',
  'approvals.reject',
  'approvals.requestInfo',
  'approvals.escalate',
  'approvals.assignReviewer',
  'approvals.sendNotification',
  'approvals.liveChat.view',
  'approvals.liveChat.send',
  'approvals.createTask',
  'approvals.createBIWarning',
  'approvals.openRelatedRecord',
  'workflow.openRelatedRecord',
  'notifications.view',
  'notifications.markRead',
  'notifications.createTask',
  'notifications.dismiss',
  'approvals.print',
  'approvals.export',
  'approvals.notificationOutbox.view',
  'approvals.audit.view',
  'approvals.approveHighRisk',
  'taskDesk.view',
  'taskDesk.create',
  'taskDesk.viewDetail',
  'taskDesk.startReview',
  'taskDesk.addNote',
  'taskDesk.reassign',
  'taskDesk.pendingInfo',
  'taskDesk.escalate',
  'taskDesk.complete',
  'taskDesk.close',
  'taskDesk.createApproval',
  'taskDesk.createBIWarning',
  'taskDesk.openRelatedRecord',
  'taskDesk.print',
  'taskDesk.export',
  'reports.sales',
  'reports.inventory',
  'ownerDesk.accountingDesk.paymentPosting.view',
  'ownerDesk.accountingDesk.paymentPosting.viewReceipts',
  'ownerDesk.accountingDesk.paymentPosting.flagVariance',
  'ownerDesk.accountingDesk.paymentPosting.addNote',
  'ownerDesk.accountingDesk.paymentPosting.createTask',
  'ownerDesk.accountingDesk.paymentPosting.createBIWarning',
  'ownerDesk.accountingDesk.paymentPosting.print',
  'ownerDesk.accountingDesk.paymentPosting.export',
  'financialControl.view',
  'financialControl.accounts.view',
  'financialControl.moneyIn.view',
  'financialControl.moneyOut.view',
  'financialControl.cashPlan.view',
  'financialControl.cashPlan.manage',
  'financialControl.profitability.view',
  'financialControl.reserveProtection.view',
  'financialControl.ownerDecisions.view',
  'financialControl.bi.view',
  'financialControl.print',
  'financialControl.export',
  'financialControl.checkWriter.view',
  'financialControl.checkWriter.create',
  'financialControl.checkWriter.prepare',
  'financialControl.checkWriter.approve',
  'financialControl.checkWriter.print',
  'financialControl.checkWriter.issueLocal',
  'financialControl.checkWriter.void',
  'financialControl.payee.view',
  'financialControl.payee.manage',
  'financialControl.checkSettings.manage',
  'financialControl.journal.view',
  'financialControl.journal.create',
  'financialControl.journal.editDraft',
  'financialControl.journal.submitReview',
  'financialControl.journal.markPostedPreview',
  'financialControl.journal.void',
  'financialControl.journal.print',
  'settings.view',
  'businessProfile.edit',
  'businessRegistration.view',
  'businessRegistration.dashboardView',
  'businessTax.view',
  'businessAdministrator.view',
  'hardware.view',
  'bi.view',
  'bi.management.view',
  'bi.management.generate',
  'bi.riskReview',
  'bi.advice.view',
  'bi.advice.generate',
  'bi.advice.assign',
  'bi.advice.resolve',
  'bi.advice.dismiss',
  'bi.advice.escalate',
  'bi.advice.createTask',
  'bi.actionPoints.view',
  'bi.actionPoints.manage',
  'bi.reorderProtection.view',
  'bi.reorderProtection.override',
  'bi.shelfStocktake.assign',
  'bi.cashRisk.view',
  'bi.staffRisk.view',
  'bi.taxReadiness.view',
  'bi.profitSnapshot.view',
  'bi.reorderBlock.review',
  'bi.reorderBlock.override'
];

const directRolePermissions: Record<SecurityRoleKey, string[]> = {
  Owner: [],
  SysAdmin: [],
  Manager: managerDirectPermissions,
  Supervisor: [
    'sales.discount',
    'sales.viewHistory',
    'shift.view',
    'shift.open',
    'shift.close',
    'shift.recovery.restore',
    'terminal.readinessCheck',
    'terminal.history.view',
    'cashDrawer.assign',
    'cashDrawer.release',
    'inventory.view',
    'productMaster.view',
    'stocktake.view',
    'delivery.view',
    'delivery.assign',
    'approvals.view',
    'approvals.viewDetail',
    'approvals.startReview',
    'approvals.approve',
    'approvals.reject',
    'approvals.requestInfo',
    'approvals.sendNotification',
    'approvals.liveChat.view',
    'approvals.liveChat.send',
    'approvals.openRelatedRecord',
    'workflow.openRelatedRecord',
    'notifications.view',
    'notifications.markRead',
    'notifications.createTask',
    'notifications.dismiss',
    'approvals.print',
    'approvals.export',
    'approvals.notificationOutbox.view',
    'approvals.audit.view',
    'approvals.approveLowRisk',
    'reports.view',
    'sync.view',
    'helpDesk.view',
    'helpDesk.print',
    'helpDesk.copy',
    'helpDesk.reportIssue',
    'helpDesk.openFunctionLinks',
    'bi.view',
    'bi.riskReview',
    'bi.advice.view',
    'bi.advice.generate',
    'bi.advice.resolve',
    'bi.advice.createTask'
  ],
  Accountant: [
    'dashboard.view',
    'sales.viewHistory',
    'sales.creditRedeem',
    'sales.accountSale',
    'sales.profitSnapshot.view',
    'sales.profitSnapshot.generate',
    'sales.profitSnapshot.export',
    'sales.profitSnapshot.print',
    'sales.miscellaneous.review',
    'reports.view',
    'reports.sales',
    'reports.accounting',
    'reports.export',
    'shift.eodReport.view',
    'shift.eodReport.print',
    'terminal.history.view',
    'accounting.view',
    'accounting.readinessReview',
    'accounting.export',
    'chartOfAccounts.view',
    'ownerDesk.accountingDesk.paymentPosting.view',
    'ownerDesk.accountingDesk.paymentPosting.markSettled',
    'ownerDesk.accountingDesk.paymentPosting.viewReceipts',
    'ownerDesk.accountingDesk.paymentPosting.flagVariance',
    'ownerDesk.accountingDesk.paymentPosting.addNote',
    'ownerDesk.accountingDesk.paymentPosting.createTask',
    'ownerDesk.accountingDesk.paymentPosting.createBIWarning',
    'ownerDesk.accountingDesk.paymentPosting.print',
    'ownerDesk.accountingDesk.paymentPosting.export',
    'financialControl.view',
    'financialControl.accounts.view',
    'financialControl.moneyIn.view',
    'financialControl.moneyOut.view',
    'financialControl.cashPlan.view',
    'financialControl.profitability.view',
    'financialControl.reserveProtection.view',
    'financialControl.ownerDecisions.view',
    'financialControl.bi.view',
    'financialControl.print',
    'financialControl.export',
    'financialControl.checkWriter.view',
    'financialControl.checkWriter.create',
    'financialControl.checkWriter.prepare',
    'financialControl.checkWriter.print',
    'financialControl.checkWriter.issueLocal',
    'financialControl.payee.view',
    'financialControl.payee.manage',
    'financialControl.journal.view',
    'financialControl.journal.create',
    'financialControl.journal.editDraft',
    'financialControl.journal.submitReview',
    'financialControl.journal.markPostedPreview',
    'financialControl.journal.print',
    'delivery.cashReview',
    'approvals.view',
    'approvals.viewDetail',
    'approvals.startReview',
    'approvals.requestInfo',
    'approvals.liveChat.view',
    'approvals.liveChat.send',
    'approvals.openRelatedRecord',
    'approvals.print',
    'approvals.export',
    'approvals.notificationOutbox.view',
    'approvals.audit.view',
    'taskDesk.view',
    'taskDesk.viewDetail',
    'taskDesk.startReview',
    'taskDesk.addNote',
    'taskDesk.complete',
    'taskDesk.openRelatedRecord',
    'workflow.openRelatedRecord',
    'notifications.view',
    'notifications.markRead',
    'sync.view',
    'helpDesk.view',
    'helpDesk.print',
    'helpDesk.copy',
    'helpDesk.reportIssue',
    'helpDesk.openFunctionLinks',
    'customers.creditView',
    'businessRegistration.view',
    'businessRegistration.dashboardView',
    'businessTax.view',
    'businessAdministrator.view',
    'bi.advice.view'
  ],
  StockController: [
    'dashboard.view',
    'inventory.view',
    'productMaster.view',
    'productMaster.create',
    'productMaster.edit',
    'inventory.product.create',
    'inventory.product.createDraft',
    'inventory.product.reviewNewFromPO',
    'purchaseOrder.productSearch',
    'purchaseOrder.productCreateFromPO',
    'productImport.view',
    'inventory.import.view',
    'inventory.import.create',
    'inventory.import.map',
    'inventory.import.template.view',
    'inventory.import.validate',
    'inventory.import.submitApproval',
    'inventory.import.export',
    'inventory.import.print',
    'inventory.import.createTask',
    'inventory.import.createBIWarning',
    'productImport.create',
    'productImport.map',
    'productImport.validate',
    'purchaseOrder.view',
    'purchaseOrder.create',
    'goodsReceiving.view',
    'goodsReceiving.create',
    'supplierReturn.view',
    'supplierReturn.create',
    'stockAdjustment.view',
    'stockAdjustment.create',
    'stocktake.view',
    'stocktake.create',
    'stockTransfer.view',
    'stockTransfer.create',
    'stockTransfer.dispatch',
    'stockTransfer.receive',
    'openingBalance.view',
    'openingBalance.create',
    'reports.inventory',
    'taskDesk.view',
    'taskDesk.viewDetail',
    'taskDesk.startReview',
    'taskDesk.addNote',
    'taskDesk.complete',
    'taskDesk.openRelatedRecord',
    'workflow.openRelatedRecord',
    'notifications.view',
    'notifications.markRead',
    'bi.view',
    'bi.advice.view',
    'bi.advice.generate',
    'bi.shelfStocktake.assign',
    'bi.reorderBlock.review',
    'sync.view',
    'sync.retry',
    'sync.batch.create',
    'helpDesk.view',
    'helpDesk.print',
    'helpDesk.copy',
    'helpDesk.reportIssue',
    'helpDesk.openFunctionLinks'
  ],
  Cashier: [
    'dashboard.view',
    'sales.open',
    'sales.complete',
    'sales.hold',
    'sales.reprintReceipt',
    'shift.view',
    'shift.open',
    'shift.close',
    'shift.recovery.restore',
    'terminal.history.view',
    'customers.view',
    'customers.createRequest',
    'delivery.create',
    'taskDesk.view',
    'taskDesk.viewDetail',
    'taskDesk.startReview',
    'taskDesk.addNote',
    'taskDesk.complete',
    'sync.view',
    'helpDesk.view',
    'helpDesk.copy',
    'helpDesk.reportIssue',
    'helpDesk.openFunctionLinks'
  ],
  DeliveryStaff: [
    'dashboard.view',
    'delivery.view',
    'delivery.track',
    'delivery.verifyCode',
    'delivery.complete',
    'bi.advice.view',
    'taskDesk.view',
    'taskDesk.viewDetail',
    'taskDesk.startReview',
    'taskDesk.addNote',
    'taskDesk.complete',
    'sync.view',
    'helpDesk.view',
    'helpDesk.copy',
    'helpDesk.reportIssue',
    'helpDesk.openFunctionLinks'
  ],
  Viewer: [
    'dashboard.view',
    'reports.view',
    'audit.view',
    'businessProfile.view',
    'helpDesk.view'
  ]
};

export function getRoleHierarchyLevel(roleKey: SecurityRoleKey): number {
  return securityRoleDefinitions.find((role) => role.roleKey === roleKey)?.hierarchyLevel || 99;
}

export function getInheritedRoles(roleKey: SecurityRoleKey): SecurityRoleKey[] {
  const role = securityRoleDefinitions.find((item) => item.roleKey === roleKey);
  if (!role) return [];
  return Array.from(new Set(role.inheritsFrom.flatMap((inheritedRole) => [inheritedRole, ...getInheritedRoles(inheritedRole)])));
}

export function roleInheritsFrom(roleKey: SecurityRoleKey, inheritedRoleKey: SecurityRoleKey): boolean {
  return getInheritedRoles(roleKey).includes(inheritedRoleKey);
}

export function getDefaultRolePermissions(roleKey: SecurityRoleKey): string[] {
  if (roleKey === 'Owner' || roleKey === 'SysAdmin') return securityRightsCatalog.map((right) => right.permissionKey);
  return Array.from(new Set([...getDirectRolePermissions(roleKey), ...getInheritedRoles(roleKey).flatMap((role) => getDirectRolePermissions(role))]));
}

export function getDirectRolePermissions(roleKey: SecurityRoleKey): string[] {
  if (roleKey === 'Owner' || roleKey === 'SysAdmin') return securityRightsCatalog.map((right) => right.permissionKey);
  return directRolePermissions[roleKey] || directRolePermissions.Viewer;
}

export function getPermissionInheritanceSource(roleKey: SecurityRoleKey, permissionKey: string): SecurityRoleKey | undefined {
  return getInheritedRoles(roleKey).find((inheritedRole) => getDirectRolePermissions(inheritedRole).includes(permissionKey));
}
