const ROOT_VENDORS = 'vendors';
const ROOT_VENDOR_USERS = 'vendorUsers';
const ROOT_STAFF = 'staff';
const ROOT_VENDOR_MEMBERSHIPS = 'vendorMemberships';

export const firestoreCollectionNames = {
  vendors: ROOT_VENDORS,
  branches: 'branches',
  warehouses: 'warehouses',
  terminals: 'terminals',
  shifts: 'shifts',
  cashDrawers: 'cashDrawers',
  productMaster: 'productMaster',
  productStockBalances: 'productStockBalances',
  productImportBatches: 'productImportBatches',
  productImportRows: 'productImportRows',
  industrialSectorTemplates: 'industrialSectorTemplates',
  customers: 'customers',
  customerAddresses: 'customerAddresses',
  customerInteractions: 'customerInteractions',
  customerRequests: 'customerRequests',
  marketplaceListings: 'marketplaceListings',
  marketplaceOrders: 'marketplaceOrders',
  marketplaceOrderLines: 'marketplaceOrderLines',
  marketplaceCategories: 'marketplaceCategories',
  marketplaceEnquiries: 'marketplaceEnquiries',
  purchaseOrders: 'purchaseOrders',
  purchaseOrderLines: 'purchaseOrderLines',
  goodsReceivingNotes: 'goodsReceivingNotes',
  goodsReceivingLines: 'goodsReceivingLines',
  supplierReturns: 'supplierReturns',
  supplierReturnLines: 'supplierReturnLines',
  stockAdjustments: 'stockAdjustments',
  stockAdjustmentLines: 'stockAdjustmentLines',
  stocktakes: 'stocktakes',
  stocktakeLines: 'stocktakeLines',
  stockTransfers: 'stockTransfers',
  stockTransferLines: 'stockTransferLines',
  inventoryMovements: 'inventoryMovements',
  productTransformations: 'productTransformations',
  productTransformationInputLines: 'productTransformationInputLines',
  productTransformationOutputLines: 'productTransformationOutputLines',
  productLedger: 'productLedger',
  salesReceipts: 'salesReceipts',
  salesReceiptLines: 'salesReceiptLines',
  payments: 'payments',
  posCashMovements: 'pos_cash_movements',
  deliveries: 'deliveries',
  deliveryLines: 'delivery_lines',
  deliveryAddresses: 'delivery_addresses',
  deliveryAssignments: 'delivery_assignments',
  deliveryTracking: 'delivery_tracking',
  deliveryConfirmations: 'delivery_confirmations',
  proofOfDelivery: 'proof_of_delivery',
  deliveryCashCollections: 'delivery_cash_collections',
  deliveryCashHandovers: 'delivery_cash_handovers',
  deliveryFailures: 'delivery_failures',
  deliveryReturns: 'delivery_returns',
  deliveryPartners: 'delivery_partners',
  deliveryPerformance: 'delivery_performance',
  deliveryRequests: 'deliveryRequests',
  deliveryProviders: 'deliveryProviders',
  deliveryTrackingEvents: 'deliveryTrackingEvents',
  approvalRequests: 'approval_requests',
  auditLogs: 'audit_logs',
  approvals: 'approvals',
  tasks: 'tasks',
  biEvents: 'biEvents',
  biRules: 'bi_rules',
  biWarnings: 'bi_warnings',
  biInsights: 'bi_insights',
  biActionRoutes: 'bi_action_routes',
  biResolutions: 'bi_resolutions',
  businessRiskScores: 'business_risk_scores',
  dailyBusinessBriefs: 'daily_business_briefs',
  auditEvents: 'auditEvents',
  offlineSyncQueue: 'offlineSyncQueue',
  syncBatches: 'syncBatches',
  syncConflicts: 'syncConflicts',
  accountingReadiness: 'accountingReadiness',
  chartOfAccounts: 'chartOfAccounts',
  vendorUsers: ROOT_VENDOR_USERS,
  vendorAppAccess: 'vendorAppAccess',
  integrationEvents: 'integrationEvents',
  staff: ROOT_STAFF,
  vendorMemberships: ROOT_VENDOR_MEMBERSHIPS,
  staffProfiles: 'staffProfiles',
  branchAccess: 'branchAccess',
  terminalAccess: 'terminalAccess',
  rolePermissionProfiles: 'rolePermissionProfiles',
  sessionAuditEvents: 'sessionAuditEvents',
} as const;

export function encodeFirestoreId(id: string | number): string {
  return encodeURIComponent(String(id || 'unassigned').trim()).replace(/\./g, '%2E');
}

const vendorPath = (vendorId: string) => `${ROOT_VENDORS}/${encodeFirestoreId(vendorId)}`;
const vendorCollection = (vendorId: string, collectionName: string) => `${vendorPath(vendorId)}/${collectionName}`;

export const firestorePaths = {
  vendor: vendorPath,
  branches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.branches),
  branch: (vendorId: string, branchId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.branches)}/${encodeFirestoreId(branchId)}`,
  terminals: (vendorId: string, branchId: string) => `${firestorePaths.branch(vendorId, branchId)}/${firestoreCollectionNames.terminals}`,
  terminal: (vendorId: string, branchId: string, terminalId: string) => `${firestorePaths.terminals(vendorId, branchId)}/${encodeFirestoreId(terminalId)}`,
  warehouses: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.warehouses),
  warehouse: (vendorId: string, warehouseId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.warehouses)}/${encodeFirestoreId(warehouseId)}`,
  shifts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.shifts),
  shift: (vendorId: string, shiftId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.shifts)}/${encodeFirestoreId(shiftId)}`,
  cashDrawers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.cashDrawers),
  cashDrawer: (vendorId: string, cashDrawerId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.cashDrawers)}/${encodeFirestoreId(cashDrawerId)}`,
  productMaster: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productMaster),
  productStockBalances: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productStockBalances),
  productStockBalance: (vendorId: string, balanceId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.productStockBalances)}/${encodeFirestoreId(balanceId)}`,
  productImportBatches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productImportBatches),
  productImportRows: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productImportRows),
  industrialSectorTemplates: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.industrialSectorTemplates),
  customers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customers),
  customerAddresses: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customerAddresses),
  customerInteractions: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customerInteractions),
  customerRequests: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customerRequests),
  marketplaceListings: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.marketplaceListings),
  marketplaceListing: (vendorId: string, listingId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.marketplaceListings)}/${encodeFirestoreId(listingId)}`,
  marketplaceOrders: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.marketplaceOrders),
  marketplaceOrder: (vendorId: string, orderId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.marketplaceOrders)}/${encodeFirestoreId(orderId)}`,
  marketplaceOrderLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.marketplaceOrderLines),
  marketplaceCategories: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.marketplaceCategories),
  marketplaceEnquiries: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.marketplaceEnquiries),
  purchaseOrders: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.purchaseOrders),
  purchaseOrderLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.purchaseOrderLines),
  goodsReceivingNotes: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingNotes),
  goodsReceivingNote: (vendorId: string, grnId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingNotes)}/${encodeFirestoreId(grnId)}`,
  goodsReceivingLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingLines),
  goodsReceivingLine: (vendorId: string, lineId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingLines)}/${encodeFirestoreId(lineId)}`,
  supplierReturns: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.supplierReturns),
  supplierReturnLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.supplierReturnLines),
  stockAdjustments: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockAdjustments),
  stockAdjustment: (vendorId: string, adjustmentId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stockAdjustments)}/${encodeFirestoreId(adjustmentId)}`,
  stockAdjustmentLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockAdjustmentLines),
  stockAdjustmentLine: (vendorId: string, lineId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stockAdjustmentLines)}/${encodeFirestoreId(lineId)}`,
  stocktakes: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stocktakes),
  stocktake: (vendorId: string, stocktakeId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stocktakes)}/${encodeFirestoreId(stocktakeId)}`,
  stocktakeLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stocktakeLines),
  stocktakeLine: (vendorId: string, lineId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stocktakeLines)}/${encodeFirestoreId(lineId)}`,
  stockTransfers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockTransfers),
  stockTransfer: (vendorId: string, transferId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stockTransfers)}/${encodeFirestoreId(transferId)}`,
  stockTransferLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockTransferLines),
  stockTransferLine: (vendorId: string, lineId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.stockTransferLines)}/${encodeFirestoreId(lineId)}`,
  inventoryMovements: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.inventoryMovements),
  inventoryMovement: (vendorId: string, movementId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.inventoryMovements)}/${encodeFirestoreId(movementId)}`,
  productTransformations: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productTransformations),
  productTransformationInputLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productTransformationInputLines),
  productTransformationOutputLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productTransformationOutputLines),
  productLedger: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productLedger),
  productLedgerEntry: (vendorId: string, ledgerId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.productLedger)}/${encodeFirestoreId(ledgerId)}`,
  salesReceipts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.salesReceipts),
  salesReceiptLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.salesReceiptLines),
  payments: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.payments),
  deliveries: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveries),
  deliveryLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryLines),
  deliveryAddresses: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryAddresses),
  deliveryAssignments: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryAssignments),
  deliveryTracking: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryTracking),
  deliveryConfirmations: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryConfirmations),
  proofOfDelivery: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.proofOfDelivery),
  deliveryCashCollections: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryCashCollections),
  deliveryCashHandovers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryCashHandovers),
  deliveryFailures: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryFailures),
  deliveryReturns: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryReturns),
  deliveryPartners: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryPartners),
  deliveryPerformance: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryPerformance),
  deliveryRequests: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryRequests),
  deliveryProviders: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryProviders),
  deliveryTrackingEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryTrackingEvents),
  approvalRequests: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.approvalRequests),
  posCashMovements: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.posCashMovements),
  auditLogs: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.auditLogs),
  approvals: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.approvals),
  tasks: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.tasks),
  biEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biEvents),
  biRules: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biRules),
  biWarnings: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biWarnings),
  biInsights: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biInsights),
  biActionRoutes: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biActionRoutes),
  biResolutions: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biResolutions),
  businessRiskScores: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.businessRiskScores),
  dailyBusinessBriefs: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.dailyBusinessBriefs),
  auditEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.auditEvents),
  offlineSyncQueue: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.offlineSyncQueue),
  syncBatches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.syncBatches),
  syncConflicts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.syncConflicts),
  accountingReadiness: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.accountingReadiness),
  chartOfAccounts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.chartOfAccounts),
  vendorUser: (userId: string) => `${ROOT_VENDOR_USERS}/${encodeFirestoreId(userId)}`,
  staff: (staffId: string) => `${ROOT_STAFF}/${encodeFirestoreId(staffId)}`,
  vendorMembership: (membershipId: string) => `${ROOT_VENDOR_MEMBERSHIPS}/${encodeFirestoreId(membershipId)}`,
  staffProfiles: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.staffProfiles),
  staffProfile: (vendorId: string, staffId: string) => `${firestorePaths.staffProfiles(vendorId)}/${encodeFirestoreId(staffId)}`,
  branchAccess: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.branchAccess),
  branchAccessRecord: (vendorId: string, branchAccessId: string) => `${firestorePaths.branchAccess(vendorId)}/${encodeFirestoreId(branchAccessId)}`,
  terminalAccess: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.terminalAccess),
  terminalAccessRecord: (vendorId: string, terminalAccessId: string) => `${firestorePaths.terminalAccess(vendorId)}/${encodeFirestoreId(terminalAccessId)}`,
  rolePermissionProfiles: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.rolePermissionProfiles),
  rolePermissionProfile: (vendorId: string, roleId: string) => `${firestorePaths.rolePermissionProfiles(vendorId)}/${encodeFirestoreId(roleId)}`,
  sessionAuditEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.sessionAuditEvents),
  sessionAuditEvent: (vendorId: string, eventId: string) => `${firestorePaths.sessionAuditEvents(vendorId)}/${encodeFirestoreId(eventId)}`,
  vendorAppAccess: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.vendorAppAccess),
  integrationEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.integrationEvents)
};
