const ROOT_VENDORS = 'vendors';
const ROOT_VENDOR_USERS = 'vendorUsers';
const ROOT_STAFF = 'staff';
const ROOT_VENDOR_MEMBERSHIPS = 'vendorMemberships';

export const firestoreCollectionNames = {
  vendors: ROOT_VENDORS,
  branches: 'branches',
  terminals: 'terminals',
  productMaster: 'productMaster',
  productStockBalances: 'productStockBalances',
  productImportBatches: 'productImportBatches',
  productImportRows: 'productImportRows',
  industrialSectorTemplates: 'industrialSectorTemplates',
  customers: 'customers',
  customerRequests: 'customerRequests',
  purchaseOrders: 'purchaseOrders',
  purchaseOrderLines: 'purchaseOrderLines',
  goodsReceivingNotes: 'goodsReceivingNotes',
  goodsReceivingLines: 'goodsReceivingLines',
  supplierReturns: 'supplierReturns',
  supplierReturnLines: 'supplierReturnLines',
  stockAdjustments: 'stockAdjustments',
  stockAdjustmentLines: 'stockAdjustmentLines',
  stocktakes: 'stocktakes',
  stocktakeLines: 'stocktakeLines',
  stockTransfers: 'stockTransfers',
  stockTransferLines: 'stockTransferLines',
  inventoryMovements: 'inventoryMovements',
  productLedger: 'productLedger',
  salesReceipts: 'salesReceipts',
  salesReceiptLines: 'salesReceiptLines',
  payments: 'payments',
  deliveryRequests: 'deliveryRequests',
  deliveryProviders: 'deliveryProviders',
  deliveryTrackingEvents: 'deliveryTrackingEvents',
  approvals: 'approvals',
  tasks: 'tasks',
  biEvents: 'biEvents',
  auditEvents: 'auditEvents',
  offlineSyncQueue: 'offlineSyncQueue',
  syncBatches: 'syncBatches',
  syncConflicts: 'syncConflicts',
  accountingReadiness: 'accountingReadiness',
  chartOfAccounts: 'chartOfAccounts',
  vendorUsers: ROOT_VENDOR_USERS,
  staff: ROOT_STAFF,
  vendorMemberships: ROOT_VENDOR_MEMBERSHIPS,
  staffProfiles: 'staffProfiles',
  branchAccess: 'branchAccess',
  terminalAccess: 'terminalAccess',
  rolePermissionProfiles: 'rolePermissionProfiles',
  sessionAuditEvents: 'sessionAuditEvents'
} as const;

export function encodeFirestoreId(id: string | number): string {
  return encodeURIComponent(String(id || 'unassigned').trim()).replace(/\./g, '%2E');
}

const vendorPath = (vendorId: string) => `${ROOT_VENDORS}/${encodeFirestoreId(vendorId)}`;
const vendorCollection = (vendorId: string, collectionName: string) => `${vendorPath(vendorId)}/${collectionName}`;

export const firestorePaths = {
  vendor: vendorPath,
  branches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.branches),
  branch: (vendorId: string, branchId: string) => `${vendorCollection(vendorId, firestoreCollectionNames.branches)}/${encodeFirestoreId(branchId)}`,
  terminals: (vendorId: string, branchId: string) => `${firestorePaths.branch(vendorId, branchId)}/${firestoreCollectionNames.terminals}`,
  terminal: (vendorId: string, branchId: string, terminalId: string) => `${firestorePaths.terminals(vendorId, branchId)}/${encodeFirestoreId(terminalId)}`,
  productMaster: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productMaster),
  productStockBalances: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productStockBalances),
  productImportBatches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productImportBatches),
  productImportRows: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productImportRows),
  industrialSectorTemplates: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.industrialSectorTemplates),
  customers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customers),
  customerRequests: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.customerRequests),
  purchaseOrders: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.purchaseOrders),
  purchaseOrderLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.purchaseOrderLines),
  goodsReceivingNotes: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingNotes),
  goodsReceivingLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.goodsReceivingLines),
  supplierReturns: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.supplierReturns),
  supplierReturnLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.supplierReturnLines),
  stockAdjustments: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockAdjustments),
  stockAdjustmentLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockAdjustmentLines),
  stocktakes: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stocktakes),
  stocktakeLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stocktakeLines),
  stockTransfers: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockTransfers),
  stockTransferLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.stockTransferLines),
  inventoryMovements: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.inventoryMovements),
  productLedger: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.productLedger),
  salesReceipts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.salesReceipts),
  salesReceiptLines: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.salesReceiptLines),
  payments: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.payments),
  deliveryRequests: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryRequests),
  deliveryProviders: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryProviders),
  deliveryTrackingEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.deliveryTrackingEvents),
  approvals: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.approvals),
  tasks: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.tasks),
  biEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.biEvents),
  auditEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.auditEvents),
  offlineSyncQueue: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.offlineSyncQueue),
  syncBatches: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.syncBatches),
  syncConflicts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.syncConflicts),
  accountingReadiness: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.accountingReadiness),
  chartOfAccounts: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.chartOfAccounts),
  vendorUser: (userId: string) => `${ROOT_VENDOR_USERS}/${encodeFirestoreId(userId)}`,
  staff: (staffId: string) => `${ROOT_STAFF}/${encodeFirestoreId(staffId)}`,
  vendorMembership: (membershipId: string) => `${ROOT_VENDOR_MEMBERSHIPS}/${encodeFirestoreId(membershipId)}`,
  staffProfiles: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.staffProfiles),
  staffProfile: (vendorId: string, staffId: string) => `${firestorePaths.staffProfiles(vendorId)}/${encodeFirestoreId(staffId)}`,
  branchAccess: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.branchAccess),
  branchAccessRecord: (vendorId: string, branchAccessId: string) => `${firestorePaths.branchAccess(vendorId)}/${encodeFirestoreId(branchAccessId)}`,
  terminalAccess: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.terminalAccess),
  terminalAccessRecord: (vendorId: string, terminalAccessId: string) => `${firestorePaths.terminalAccess(vendorId)}/${encodeFirestoreId(terminalAccessId)}`,
  rolePermissionProfiles: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.rolePermissionProfiles),
  rolePermissionProfile: (vendorId: string, roleId: string) => `${firestorePaths.rolePermissionProfiles(vendorId)}/${encodeFirestoreId(roleId)}`,
  sessionAuditEvents: (vendorId: string) => vendorCollection(vendorId, firestoreCollectionNames.sessionAuditEvents),
  sessionAuditEvent: (vendorId: string, eventId: string) => `${firestorePaths.sessionAuditEvents(vendorId)}/${encodeFirestoreId(eventId)}`
};
