import { ClipboardCheck, X } from 'lucide-react';
import type { BIAdviceRecord, BIShelfStocktakeAssignment } from '../types';

interface BIShelfStocktakeAssignmentModalProps {
  assignment: BIShelfStocktakeAssignment | null;
  advice?: BIAdviceRecord | null;
  onStart: () => void;
  onMarkInProgress: () => void;
  onMarkCompleted: () => void;
  onClose: () => void;
}

export default function BIShelfStocktakeAssignmentModal({
  assignment,
  advice,
  onStart,
  onMarkInProgress,
  onMarkCompleted,
  onClose
}: BIShelfStocktakeAssignmentModalProps) {
  if (!assignment) return null;

  return (
    <div className="shift-control-modal-backdrop" role="presentation">
      <section className="shift-control-modal" role="dialog" aria-modal="true" aria-labelledby="bi-shelf-stocktake-title">
        <header className="shift-control-modal__header">
          <div>
            <p className="sci-pos-eyebrow">Daily rotating shelf count generated by BI rules.</p>
            <h2 id="bi-shelf-stocktake-title"><ClipboardCheck size={18} aria-hidden="true" /> Shelf Stocktake Assignment</h2>
          </div>
          <button type="button" className="sci-icon-button" onClick={onClose} aria-label="Close shelf stocktake assignment">
            <X size={18} aria-hidden="true" />
          </button>
        </header>
        <div className="shift-control-modal__body">
          <div className="shift-history-detail-grid">
            <div><span>Assigned Date</span><strong>{assignment.assignedDate}</strong></div>
            <div><span>Branch</span><strong>{assignment.branchName}</strong></div>
            <div><span>Warehouse</span><strong>{assignment.warehouseId}</strong></div>
            <div><span>Shelf / Bin</span><strong>{assignment.shelfLocation}</strong></div>
            <div><span>Item Count</span><strong>{assignment.itemCount}</strong></div>
            <div><span>Assigned Staff</span><strong>{assignment.assignedStaffName}</strong></div>
            <div><span>Status</span><strong>{assignment.status}</strong></div>
            <div><span>Reason</span><strong>{assignment.reason}</strong></div>
          </div>
          <div className="bi-advice-narrative">
            <strong>BI Advice Narrative</strong>
            <p>{advice?.narrative || 'Monthly rotating shelf stocktake assignment generated by deterministic BI rules.'}</p>
            <small>{advice?.notes || 'Risk notes: count shelf quantity and confirm stock condition before close.'}</small>
          </div>
          <footer className="shift-control-modal__footer">
            <button type="button" className="sci-pos-button sci-pos-button--primary" onClick={onStart}>Start Stocktake</button>
            <button type="button" className="sci-pos-button sci-pos-button--secondary" onClick={onMarkInProgress}>Mark In Progress</button>
            <button type="button" className="sci-pos-button sci-pos-button--secondary" onClick={onMarkCompleted}>Mark Completed</button>
            <button type="button" className="sci-pos-button sci-pos-button--secondary" onClick={onClose}>Reassign</button>
            <button type="button" className="sci-pos-button sci-pos-button--secondary" onClick={onClose}>Close</button>
          </footer>
        </div>
      </section>
    </div>
  );
}
