import React from 'react';
import { Printer, X } from 'lucide-react';
import type { InventoryReportPayload } from '../types';

interface InventoryReportPrintViewProps {
  open: boolean;
  payload: InventoryReportPayload | null;
  pdfMode?: boolean;
  onClose: () => void;
  onPrinted?: () => void;
}

function activeFilters(payload: InventoryReportPayload): string[] {
  return Object.entries(payload.filters)
    .filter(([, value]) => value !== undefined && value !== '' && value !== 'ALL' && value !== false)
    .map(([key, value]) => `${key}: ${String(value)}`);
}

export default function InventoryReportPrintView({
  open,
  payload,
  pdfMode = false,
  onClose,
  onPrinted
}: InventoryReportPrintViewProps) {
  if (!open || !payload) return null;

  const handlePrint = () => {
    window.print();
    onPrinted?.();
  };

  return (
    <div className="inventory-report-print-modal">
      <div className="inventory-report-print-shell">
        <div className="inventory-report-print-toolbar no-print">
          <div>
            <h2>{payload.reportName}</h2>
            <p>{pdfMode ? 'Choose Print and select Save as PDF on this device.' : 'Device print view prepared.'}</p>
          </div>
          <div className="inventory-report-print-actions">
            <button type="button" onClick={handlePrint}><Printer className="w-4 h-4" /> Open Print / Save as PDF</button>
            <button type="button" onClick={onClose} aria-label="Close report print view"><X className="w-4 h-4" /></button>
          </div>
        </div>

        <article className="inventory-report-print-page">
          <header className="inventory-report-print-header">
            <div>
              <div className="inventory-report-print-brand">{payload.vendorName}</div>
              <h1>{payload.reportName}</h1>
              <p>{payload.notes}</p>
            </div>
            <div className="inventory-report-print-meta">
              <span>Generated: {new Date(payload.generatedAt).toLocaleString()}</span>
              <span>Generated By: {payload.generatedBy}</span>
              <span>Branch: {payload.branchName}</span>
              <span>Warehouse: {payload.warehouseName}</span>
            </div>
          </header>

          <section className="inventory-report-print-summary">
            {payload.summaryMetrics.map((metric) => (
              <div key={metric.label}>
                <span>{metric.label}</span>
                <strong>{metric.value}</strong>
              </div>
            ))}
          </section>

          <section className="inventory-report-print-filters">
            <strong>Active Filters</strong>
            <p>{activeFilters(payload).join(' | ') || 'None'}</p>
          </section>

          <table className="inventory-report-print-table">
            <thead>
              <tr>
                {payload.columns.map((column) => <th key={column.key}>{column.label}</th>)}
              </tr>
            </thead>
            <tbody>
              {payload.rows.length === 0 ? (
                <tr><td colSpan={payload.columns.length}>No report rows matched the selected filters.</td></tr>
              ) : payload.rows.map((row) => (
                <tr key={row.rowId}>
                  {payload.columns.map((column) => <td key={column.key}>{String(row.values[column.key] ?? '-')}</td>)}
                </tr>
              ))}
            </tbody>
          </table>

          <footer className="inventory-report-print-footer">
            iTred Commerce POS - Inventory Report | Build Development / Local Report | {payload.reportId}
          </footer>
        </article>
      </div>
    </div>
  );
}
