import type { SupplierStatementRecord } from '../types';

const money = (value: number) => `$${value.toFixed(2)}`;

export default function SupplierStatementDocument({ statement }: { statement: SupplierStatementRecord }) {
  const billTotal = statement.bills.reduce((sum, bill) => sum + bill.originalAmount, 0);
  const paymentTotal = statement.payments.reduce((sum, payment) => sum + payment.amount, 0);
  const overdue = statement.bills.filter((bill) => bill.overdueDays > 0).reduce((sum, bill) => sum + bill.outstandingAmount, 0);
  return (
    <article className="supplier-statement-document">
      <header>
        <div><span>Vendor</span><strong>iTred Commerce POS</strong></div>
        <div><span>Supplier</span><strong>{statement.supplierName}</strong></div>
        <div><span>Period</span><strong>{statement.periodFrom} to {statement.periodTo}</strong></div>
      </header>
      <section className="creditors-summary-grid">
        <div className="creditors-summary-card"><span>Opening Balance</span><strong>{money(statement.openingBalance)}</strong></div>
        <div className="creditors-summary-card"><span>Supplier Bills</span><strong>{money(billTotal)}</strong></div>
        <div className="creditors-summary-card"><span>Payments</span><strong>{money(paymentTotal)}</strong></div>
        <div className="creditors-summary-card"><span>Closing Balance</span><strong>{money(statement.closingBalance)}</strong></div>
        <div className="creditors-summary-card"><span>Overdue Balance</span><strong>{money(overdue)}</strong></div>
      </section>
      <table className="creditors-table"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{statement.bills.map((bill) => <tr key={bill.billId}><td>{bill.billDate}</td><td>Supplier Bill</td><td>{bill.billNumber}</td><td>{money(bill.originalAmount)}</td><td>{money(bill.paidAmount)}</td><td>{money(bill.outstandingAmount)}</td></tr>)}{statement.payments.map((payment) => <tr key={payment.paymentId}><td>{payment.paymentDate}</td><td>Payment</td><td>{payment.paymentNumber}</td><td>{money(0)}</td><td>{money(payment.amount)}</td><td>-</td></tr>)}</tbody></table>
      <footer>Generated by {statement.generatedBy} on {new Date(statement.generatedAt).toLocaleString()}. Payment instruction placeholder only.</footer>
    </article>
  );
}
