import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { SharedCustomerAddressRecord, SharedCustomerInteractionRecord, SharedCustomerRecord, SharedCustomerRequestRecord } from '../firebase/commerceDataContract';
import type { CustomerListFilters } from '../repositories/CustomerRepository';
import { createRepositoryBundle } from '../repositories/repositoryFactory';
import { validateRepositoryOperationContext, type RepositoryOperationContext, type RepositorySubscription } from '../repositories/repositoryContext';
import { appendCustomerInteractionCommand, createCustomerAddressCommand, createCustomerCommand, createCustomerRequestCommand, deactivateCustomerCommand, loadCustomerMaster, loadCustomerRequests, searchCustomerMaster, updateCustomerAddressCommand, updateCustomerCommand, updateCustomerRequestCommand, type CustomerMasterResult } from '../services/customerMasterService';

export function useCustomerMasterData({ context }: { context: RepositoryOperationContext }) {
  const [customers, setCustomers] = useState<SharedCustomerRecord[]>([]); const [customerRequests, setCustomerRequests] = useState<SharedCustomerRequestRecord[]>([]);
  const [loading, setLoading] = useState(true); const [synchronizing, setSynchronizing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [filters, setFilters] = useState<CustomerListFilters>({});
  const bundle = useMemo(() => createRepositoryBundle(), []); const subscriptions = useRef<RepositorySubscription[]>([]); const mounted = useRef(true);
  const valid = useMemo(() => { try { validateRepositoryOperationContext(context); return true; } catch { return false; } }, [context]);
  const refresh = useCallback(async () => { if (!valid) { setError('Missing or invalid vendor context.'); setLoading(false); return; } setSynchronizing(true); const [master, requests] = await Promise.all([loadCustomerMaster(context, filters), loadCustomerRequests(context)]); if (!mounted.current) return; if (master.success && requests.success) { setCustomers(master.records); setCustomerRequests(requests.records); setError(null); } else setError(master.errorMessage || requests.errorMessage || 'Customer master could not be loaded.'); setSynchronizing(false); setLoading(false); }, [context, filters, valid]);
  useEffect(() => { mounted.current = true; void refresh(); if (valid) { subscriptions.current = [bundle.customers.subscribeCustomers(context, (rows) => mounted.current && setCustomers(rows)), bundle.customers.subscribeCustomerRequests(context, (rows) => mounted.current && setCustomerRequests(rows))]; } return () => { mounted.current = false; subscriptions.current.forEach((item) => item.unsubscribe()); subscriptions.current = []; }; }, [bundle, context, refresh, valid]);
  const save = useCallback(async <T,>(operation: () => Promise<CustomerMasterResult<T>>) => { if (!valid) return { success: false, errorCode: 'VALIDATION_ERROR', errorMessage: 'Missing or invalid vendor context.' } as CustomerMasterResult<T>; setSaving(true); try { const result = await operation(); if (mounted.current && !result.success) setError(result.errorMessage || 'Customer operation failed.'); return result; } finally { if (mounted.current) setSaving(false); } }, [valid]);
  return { customers, customerRequests, loading, synchronizing, saving, error, filters, setFilters, search: (term: string) => searchCustomerMaster(context, term, filters).then((result) => result.records), refresh,
    createCustomer: (input: Partial<SharedCustomerRecord>) => save(() => createCustomerCommand(context, input)), updateCustomer: (id: string, changes: Partial<SharedCustomerRecord>) => save(() => updateCustomerCommand(context, id, changes)), deactivateCustomer: (id: string) => save(() => deactivateCustomerCommand(context, id)),
    createAddress: (input: Partial<SharedCustomerAddressRecord>) => save(() => createCustomerAddressCommand(context, input)), updateAddress: (id: string, changes: Partial<SharedCustomerAddressRecord>) => save(() => updateCustomerAddressCommand(context, id, changes)), appendInteraction: (input: Partial<SharedCustomerInteractionRecord>) => save(() => appendCustomerInteractionCommand(context, input)),
    createRequest: (input: Partial<SharedCustomerRequestRecord>) => save(() => createCustomerRequestCommand(context, input)), updateRequest: (id: string, changes: Partial<SharedCustomerRequestRecord>) => save(() => updateCustomerRequestCommand(context, id, changes)) };
}
