import type { GoodsReceivingLine, GoodsReceivingNote, PurchaseOrder, PurchaseOrderLine, SupplierReturn, SupplierReturnLine } from '../../types';
import type { CreatePurchaseOrderCommand, PostGoodsReceiptCommand, PostSupplierReturnCommand, PurchasingSupplier, PurchasingSupplierCreditNote, PurchasingSupplierPayment, ReverseSupplierPaymentCommand } from '../../repositories/PurchasingRepository';
import type { PurchasingMigrationRecord } from './types';

export type CanonicalPurchasingMigrationPayload = PurchasingSupplier | CreatePurchaseOrderCommand | PostGoodsReceiptCommand | PostSupplierReturnCommand | PurchasingSupplierPayment | PurchasingSupplierCreditNote | ReverseSupplierPaymentCommand;
export class PurchasingMigrationTranslationError extends Error { constructor(public readonly code: 'SCOPE_MISMATCH' | 'UNSUPPORTED_STATUS' | 'INVALID_QUANTITY' | 'INVALID_MONEY' | 'MISSING_REFERENCE' | 'UNSUPPORTED_RECORD_TYPE', message: string) { super(message); this.name = 'PurchasingMigrationTranslationError'; } }
export type PurchasingMigrationDependencyResolver = (recordType: PurchasingMigrationRecord['recordType'], legacyId: string) => string;
const money = (value: unknown, field: string): number => { const number = Number(value); if (!Number.isFinite(number) || number < 0) throw new PurchasingMigrationTranslationError('INVALID_MONEY', `${field} must be finite and non-negative.`); return Math.round(number * 100) / 100; };
const positive = (value: unknown, field: string): number => { const number = Number(value); if (!Number.isFinite(number) || number <= 0) throw new PurchasingMigrationTranslationError('INVALID_QUANTITY', `${field} must be greater than zero.`); return Number(number.toFixed(6)); };
const object = (value: unknown, field: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new PurchasingMigrationTranslationError('MISSING_REFERENCE', `${field} is required.`); return value as Record<string, unknown>; };
const rows = (value: unknown, field: string): Record<string, unknown>[] => { if (!Array.isArray(value) || !value.length) throw new PurchasingMigrationTranslationError('MISSING_REFERENCE', `${field} must contain records.`); return value.map(row => object(row, field)); };
const required = (value: unknown, field: string): string => { if (typeof value !== 'string' || !value.trim()) throw new PurchasingMigrationTranslationError('MISSING_REFERENCE', `${field} is required.`); return value.trim(); };

export function translatePurchasingMigrationRecord(record: PurchasingMigrationRecord, destinationId: string, resolve: PurchasingMigrationDependencyResolver = (_type, id) => id): CanonicalPurchasingMigrationPayload {
  const p = structuredClone(record.payload); if (p.vendorId && p.vendorId !== record.vendorId) throw new PurchasingMigrationTranslationError('SCOPE_MISMATCH', 'Payload vendor does not match migration vendor.'); if (record.branchId && p.branchId && p.branchId !== record.branchId) throw new PurchasingMigrationTranslationError('SCOPE_MISMATCH', 'Payload branch does not match migration branch.');
  if (record.recordType === 'supplier') return { ...p, supplierId: destinationId, sciId: destinationId, vendorId: record.vendorId } as unknown as PurchasingSupplier;
  if (record.recordType === 'purchaseOrder') {
    if (p.status && !['Draft', 'Submitted', 'Pending Approval'].includes(String(p.status))) throw new PurchasingMigrationTranslationError('UNSUPPORTED_STATUS', 'Only draft or submitted purchase orders may be migrated.');
    const rawOrder = object(p.order || p, 'purchase order'), rawLines = rows(p.lines || rawOrder.lines, 'purchase order lines');
    const lines = rawLines.map((line, index) => { const qty = positive(line.qtyOrdered ?? line.quantityOrdered, `lines[${index}].qtyOrdered`), cost = money(line.unitCost ?? line.estimatedUnitCost, `lines[${index}].unitCost`); return { ...line, lineId: String(line.lineId || `${destinationId}_line_${index + 1}`), poId: destinationId, vendorId: record.vendorId, qtyOrdered: qty, qtyReceived: 0, qtyOutstanding: qty, estimatedUnitCost: cost, unitCost: cost, estimatedLineTotal: money(qty * cost, 'line total'), lineTotal: money(qty * cost, 'line total'), lineStatus: 'Open' } as unknown as PurchaseOrderLine; });
    const subtotal = money(lines.reduce((sum, line) => sum + Number(line.lineTotal), 0), 'subtotal'); const tax = money(rawOrder.vatTotal ?? rawOrder.taxEstimate ?? 0, 'tax');
    return { order: { ...rawOrder, poId: destinationId, vendorId: record.vendorId, branchId: record.branchId || required(rawOrder.branchId, 'branchId'), supplierId: resolve('supplier', required(rawOrder.supplierId, 'supplierId')), status: 'Draft', currency: String(rawOrder.currency || 'USD').toUpperCase(), subtotalEstimate: subtotal, subtotal, taxEstimate: tax, vatTotal: tax, grandTotalEstimate: money(subtotal + tax, 'grand total'), grandTotal: money(subtotal + tax, 'grand total') } as unknown as PurchaseOrder, lines };
  }
  if (record.recordType === 'grn') {
    if (p.receivingStatus && !['Draft', 'Pending Approval', 'Posted', 'Partially Posted'].includes(String(p.receivingStatus))) throw new PurchasingMigrationTranslationError('UNSUPPORTED_STATUS', 'Unsupported GRN status.'); const receipt = object(p.receipt || p, 'receipt'), rawLines = rows(p.lines || receipt.lines, 'GRN lines');
    return { receipt: { ...receipt, grnId: destinationId, vendorId: record.vendorId, branchId: record.branchId || required(receipt.branchId, 'branchId'), poId: resolve('purchaseOrder', required(receipt.poId, 'poId')), supplierId: resolve('supplier', required(receipt.supplierId, 'supplierId')), receivingStatus: 'Draft', postingStatus: 'Draft' } as unknown as GoodsReceivingNote, lines: rawLines.map((line, index) => ({ ...line, lineId: String(line.lineId || `${destinationId}_line_${index + 1}`), grnId: destinationId, poLineId: required(line.poLineId, `lines[${index}].poLineId`), productId: required(line.productId, `lines[${index}].productId`), qtyAccepted: positive(line.qtyAccepted ?? line.quantityAccepted, `lines[${index}].qtyAccepted`), receivedUnitCost: money(line.receivedUnitCost ?? line.unitCost, `lines[${index}].unitCost`) } as unknown as GoodsReceivingLine)), createSupplierInvoice: Boolean(receipt.supplierInvoiceNumber) };
  }
  if (record.recordType === 'supplierReturn') { const value = object(p.supplierReturn || p, 'supplier return'), rawLines = rows(p.lines || value.lines, 'return lines'); return { supplierReturn: { ...value, supplierReturnId: destinationId, vendorId: record.vendorId, branchId: record.branchId || required(value.branchId, 'branchId'), grnId: required(value.grnId, 'grnId'), supplierId: required(value.supplierId, 'supplierId'), status: 'Approved', totalReturnValue: money(rawLines.reduce((sum, line) => sum + positive(line.qtyReturnApproved, 'return quantity') * money(line.unitCost, 'return unit cost'), 0), 'return total') } as unknown as SupplierReturn, lines: rawLines.map((line, index) => ({ ...line, lineId: String(line.lineId || `${destinationId}_line_${index + 1}`), supplierReturnId: destinationId, grnLineId: required(line.grnLineId, `lines[${index}].grnLineId`), productId: required(line.productId, `lines[${index}].productId`), qtyReturnApproved: positive(line.qtyReturnApproved, `lines[${index}].qtyReturnApproved`), unitCost: money(line.unitCost, `lines[${index}].unitCost`) } as unknown as SupplierReturnLine)) }; }
  if (record.recordType === 'supplierPayment') { if (p.status && p.status !== 'POSTED') throw new PurchasingMigrationTranslationError('UNSUPPORTED_STATUS', 'Only posted supplier payments may be migrated.'); return { ...p, paymentId: destinationId, vendorId: record.vendorId, supplierId: required(p.supplierId, 'supplierId'), invoiceId: required(p.invoiceId, 'invoiceId'), amount: positive(p.amount, 'amount'), currency: String(p.currency || 'USD').toUpperCase(), status: 'POSTED' } as unknown as PurchasingSupplierPayment; }
  if (record.recordType === 'supplierCreditNote') return { ...p, creditNoteId: destinationId, vendorId: record.vendorId, supplierId: required(p.supplierId, 'supplierId'), amount: positive(p.amount, 'amount'), currency: String(p.currency || 'USD').toUpperCase(), reason: required(p.reason, 'reason'), status: 'POSTED' } as unknown as PurchasingSupplierCreditNote;
  if (record.recordType === 'paymentReversal') { const originalPaymentId = required(p.originalPaymentId, 'originalPaymentId'); return { reversal: { ...p, reversalId: originalPaymentId, originalPaymentId, vendorId: record.vendorId, supplierId: required(p.supplierId, 'supplierId'), invoiceId: required(p.invoiceId, 'invoiceId'), amount: positive(p.amount, 'amount'), currency: String(p.currency || 'USD').toUpperCase(), reason: required(p.reason, 'reason'), status: 'POSTED' } } as unknown as ReverseSupplierPaymentCommand; }
  throw new PurchasingMigrationTranslationError('UNSUPPORTED_RECORD_TYPE', `${record.recordType} is not supported by the canonical adapter.`);
}
