import type { CanonicalSaleLineInput, CanonicalSaleTotals } from './salesTypes';
import { CanonicalSalesError } from './salesErrors';
const integer = (value: number, field: string, allowZero = true) => { if (!Number.isSafeInteger(value) || value < 0 || (!allowZero && value === 0)) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', `${field} must be a safe non-negative minor-unit integer.`); return value; };
export function calculateCanonicalSalesTotals(lines: CanonicalSaleLineInput[], orderDiscountMinor = 0, amountTenderedMinor = 0): CanonicalSaleTotals {
  if (!lines.length) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', 'A sale requires at least one line.'); integer(orderDiscountMinor, 'orderDiscountMinor'); integer(amountTenderedMinor, 'amountTenderedMinor');
  let subtotalMinor = 0, lineDiscountMinor = 0, taxMinor = 0;
  for (const line of lines) { if (!Number.isFinite(line.quantity) || line.quantity <= 0) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', 'Sale quantities must be finite and greater than zero.'); integer(line.unitPriceMinor, 'unitPriceMinor'); const discount = integer(line.discountMinor || 0, 'discountMinor'); const subtotal = Math.round(line.quantity * line.unitPriceMinor); if (discount > subtotal) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', 'Line discount cannot exceed line subtotal.'); const rate = integer(line.taxRateBasisPoints || 0, 'taxRateBasisPoints'); if (rate > 10000) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', 'Tax rate is invalid.'); subtotalMinor += subtotal; lineDiscountMinor += discount; taxMinor += Math.round((subtotal - discount) * rate / 10000); }
  const discountMinor = lineDiscountMinor + orderDiscountMinor; if (discountMinor > subtotalMinor) throw new CanonicalSalesError('SALES_VALIDATION_FAILED', 'Discount cannot exceed sale subtotal.'); const taxableMinor = subtotalMinor - discountMinor; const grossMinor = subtotalMinor + taxMinor; const netMinor = taxableMinor + taxMinor; const amountPaidMinor = Math.min(amountTenderedMinor, netMinor); return { subtotalMinor, discountMinor, taxableMinor, taxMinor, grossMinor, netMinor, amountPaidMinor, amountDueMinor: Math.max(0, netMinor - amountPaidMinor), changeDueMinor: Math.max(0, amountTenderedMinor - netMinor) };
}
