import type { CanonicalBIEvent } from './biEventService';
import type { BIWarning } from './biWarningService';
export interface BusinessPeriodMetrics { sales: number; grossProfit: number; transactionCount: number; returns: number; discounts: number; cashVariance: number; stockLoss: number; overdueDebt: number; supplierOverdue: number; deliveryCompleted: number; }
export interface PeriodComparison { metric: keyof BusinessPeriodMetrics; current: number; previous: number; change: number; percentageChange?: number; explanation: string; }
export interface DailyBusinessBrief { vendorId: string; branchId?: string; businessDate: string; salesSummary: string; profitSummary: string; cashSummary: string; stockSummary: string; customerSummary: string; supplierSummary: string; deliverySummary: string; staffSummary: string; criticalWarnings: string[]; recommendedActions: string[]; generatedAt: string; }
export function compareBusinessPeriods(current: BusinessPeriodMetrics, previous: BusinessPeriodMetrics): PeriodComparison[] {
  return (Object.keys(current) as Array<keyof BusinessPeriodMetrics>).map((metric) => { const change = current[metric] - previous[metric]; const percentageChange = previous[metric] === 0 ? undefined : Math.round((change / Math.abs(previous[metric])) * 1000) / 10; return { metric, current: current[metric], previous: previous[metric], change, percentageChange, explanation: previous[metric] === 0 ? `${label(metric)} is ${current[metric]}; no percentage is shown because the previous base was zero.` : `${label(metric)} ${change >= 0 ? 'increased' : 'decreased'} by ${Math.abs(percentageChange || 0)}% over the equivalent previous period.` }; });
}
export function generateDailyBusinessBrief(input: { vendorId: string; branchId?: string; businessDate: string; events: CanonicalBIEvent[]; warnings: BIWarning[]; currency?: string }): DailyBusinessBrief {
  const events = input.events.filter((e) => e.vendorId === input.vendorId && (!input.branchId || e.branchId === input.branchId) && e.occurredAt.slice(0,10) === input.businessDate); const warnings = input.warnings.filter((w) => w.vendorId === input.vendorId && (!input.branchId || w.branchId === input.branchId)); const currency = input.currency || 'USD';
  const sum = (types: string[]) => events.filter((e) => types.includes(e.eventType)).reduce((total,e) => total + (e.amount || 0),0); const count = (types: string[]) => events.filter((e) => types.includes(e.eventType)).length;
  const critical = warnings.filter((w) => w.severity === 'Critical' && w.status !== 'Resolved' && w.status !== 'Dismissed');
  return { vendorId: input.vendorId, branchId: input.branchId, businessDate: input.businessDate,
    salesSummary: `${count(['SALE_COMPLETED'])} sales completed for ${currency} ${sum(['SALE_COMPLETED']).toFixed(2)}; ${count(['SALE_RETURNED'])} returns recorded.`,
    profitSummary: `${count(['LOW_MARGIN_SALE'])} low-margin sales need review.`, cashSummary: `${count(['CASH_VARIANCE_FOUND','CASH_SHORTAGE','CASH_OVERAGE'])} cash variances totalling ${currency} ${Math.abs(sum(['CASH_VARIANCE_FOUND','CASH_SHORTAGE','CASH_OVERAGE'])).toFixed(2)}.`,
    stockSummary: `${count(['LOW_STOCK'])} low-stock and ${count(['OUT_OF_STOCK'])} out-of-stock events were recorded.`, customerSummary: `${count(['CUSTOMER_OVERDUE','BROKEN_PROMISE_TO_PAY'])} overdue customer actions need attention.`, supplierSummary: `${count(['SUPPLIER_PAYMENT_OVERDUE'])} supplier payments are overdue.`, deliverySummary: `${count(['DELIVERY_COMPLETED'])} deliveries completed; ${count(['DELIVERY_FAILED','DELIVERY_DELAYED'])} failed or delayed.`, staffSummary: `${count(['STAFF_LOGIN_FAILED'])} failed staff login events and ${count(['HIGH_DISCOUNT_APPLIED'])} high-discount events were recorded.`, criticalWarnings: critical.map((w) => w.summary), recommendedActions: [...new Set(critical.flatMap((w) => w.recommendedActions))].slice(0,5), generatedAt: new Date().toISOString() };
}
function label(metric: string) { return metric.replace(/([A-Z])/g, ' $1').toLowerCase(); }
